resource_group_name              = "qa-resource-group"
location                         = "West US"
vm_name                          = "qa-vm"
vm_size                          = "Standard_DS2_v2"
key_vault_name                   = "qa-key-vault"
storage_account_name             = "qastorageaccount"
storage_account_tier             = "Standard"
storage_account_replication_type = "GRS"
